In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

calculate dot product


In [5]:
query=inputs[1]
attn_scores_2=torch.empty(inputs.shape[0])
for i ,x_i in enumerate(inputs):
    attn_scores_2[i]=torch.dot(query,x_i)

print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


Normalize The Attension Scores

In [9]:
attension_score_nomalize_temp=attn_scores_2/attn_scores_2.sum()

In [10]:
print("Attension Weights:",attension_score_nomalize_temp)
print("Sum of Attention Weights:", attension_score_nomalize_temp.sum())

Attension Weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum of Attention Weights: tensor(1.0000)


lets Use Softmax Normalization

In [14]:
def softmax(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)#dim=0 means sum of each column


attension_score_nomalize=softmax(x=attn_scores_2)
print("Attension Weights:",attension_score_nomalize)
print("Sum of Attention Weights:", attension_score_nomalize.sum())

Attension Weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum of Attention Weights: tensor(1.)


Softmanx Normalization using the Function


In [15]:
attention_normalized=torch.nn.functional.softmax(attn_scores_2,dim=0)
print("Attension Weights:",attention_normalized)
print("Sum of Attention Weights:", attention_normalized.sum())

Attension Weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum of Attention Weights: tensor(1.)


Calculate the Attetion Weights 


In [47]:
query= inputs[1]
context_vector_2=torch.zeros(query.shape)

for i, x_i in enumerate(inputs):
    context_vector_2+=attension_score_nomalize[i]*x_i
print("context Vectors:",context_vector_2)    

context Vectors: tensor([0.4419, 0.6515, 0.5683])


In [49]:
attn_scores=torch.empty(6,6)

for i ,x_i in enumerate(inputs):
    for j,x_j in enumerate(inputs):
        attn_scores[i,j]=torch.dot(x_i,x_j)

print(attn_scores)        

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


Do the same operation using the easier computation

In [50]:
attn_scores_z=inputs @ inputs.T

In [52]:
attn_scores_z

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [57]:
attn_weights_normalized=torch.softmax(attn_scores,dim=-1)
print(attn_weights_normalized)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [60]:
print(attn_weights_normalized.sum(dim=-1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


calculating the context Vectors 


In [64]:
context_vectors=attn_weights_normalized @ inputs

print(context_vectors)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
